// Action Types
export const SELECT_UPDATE_FILTER = 'SELECT_UPDATE_FILTER';
export const SELECT_UPDATE_CHARACTERS = 'SELECT_UPDATE_CHARACTERS';
export const SELECT_SET_CHARACTERS = 'SELECT_SET_CHARACTERS';
