# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'T7Chicken' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for T7Chicken
  target 'T7ChickenTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
