export default const inputs = {
  one: require('./1.png'),
  two: require('./2.png'),
  three: require('./3.png'),
  four: require('./4.png'),
  oneplustwo: require('./1+2.png'),
  threeplusfour: require('./3+4.png'),
  oneplustwoplusthree: require('./1+2+3.png'),
  oneplustwoplusthreeplusfour: require('./1+2+3+4.png'),
  twoplusthreeplusfour: require('./2+3+4.png'),
  u: require('./u.png'),
  u_hold: require('./u_h.png'),
  d: require('.d.png'),
  d_hold: require('./d_h.png'),
  b: require('./b.png'),
  b_hold: require('./b_h.png'),
  f: require('./f.png'),
  f_hold: require('./f_h.png'),
  ub: require('./ub.png'),
  ub_hold: require('./ub_h.png'),
  uf: require('./uf.png'),
  uf_hold: require('./uf_h.png'),
  df: require('./df.png'),
  df_hold: require('./df_h.png'),
  db: require('./db.png'),
  df_hold: require('./db_h.png')
};
