const headshots = {
  akuma: require('./akuma.png'),
  alisa: require('./alisa.png'),
  asuka: require('./asuka.png'),
  bob: require('./bob.png'),
  bryan: require('./bryan.png'),
  claudio: require('./claudio.png'),
  "devil-jin": require('./deviljin.png'),
  dragunov: require('./dragunov.png'),
  eddy: require('./eddy.png'),
  eliza: require('./eliza.png'),
  feng: require('./feng.png'),
  heihachi: require('./heihachi.png'),
  hwoarang: require('./hwoarang.png'),
  "jack-7": require('./jack7.png'),
  jin: require('./jin.png'),
  katarina: require('./katarina.png'),
  kazumi: require('./kazumi.png'),
  kazuya: require('./Tile-Kazuya.png'),
  king: require('./king.png'),
  kuma: require('./kuma.png'),
  law: require('./law.png'),
  lee: require('./lee.png'),
  lili: require('./lili.png'),
  "lucky-chloe": require('./luckychloe.png'),
  dragunov: require('./dragunov.png'),
  gigas: require('./gigas.png'),
  "jack-7": require('./jack7.png'),
  josie: require('./josie.png'),
  lars: require('./lars.png'),
  leo: require('./leo.png'),
  "master-raven": require('./masterraven.png'),
  panda: require('./panda.png'),
  paul: require('./paul.png'),
  shaheen: require('./shaheen.png'),
  steve: require('./steve.png'),
  ling: require('./ling.png'),
  miguel: require('./miguel.png'),
  nina: require('./nina.png'),
  yoshimitsu: require('./yoshimitsu.png'),
};

export default headshots;
