const headshots = {
  akuma: require('./akuma.png'),
  alisa: require('./alisa.png'),
  asuka: require('./asuka.png'),
  bob: require('./bob.png'),
  bryan: require('./bryan.png'),
  deviljin: require('./deviljin.png'),
  eddy: require('./eddy.png'),
  feng: require('./feng.png'),
  heihachi: require('./heihachi.png'),
  jin: require('./jin.png'),
  kazumi: require('./kazumi.png'),
  kazuya: require('./Tile-Kazuya.png'),
  kuma: require('./kuma.png'),
  law: require('./law.png'),
  lee: require('./lee.png'),
  lili: require('./lili.png'),
  dragunov: require('./dragunov.png'),
  gigas: require('./gigas.png'),
  jack7: require('./jack7.png'),
  lars: require('./lars.png'),
  masterraven: require('./masterraven.png'),
  panda: require('./panda.png'),
  paul: require('./paul.png'),
  steve: require('./steve.png'),
  ling: require('./ling.png'),
  miguel: require('./miguel.png'),
  nina: require('./nina.png'),
  yoshimitsu: require('./yoshimitsu.png'),
};

export default headshots;
